site_name: The PTC cluster at IBS-CTPU
site_url: https://github.com/cbpark/ptc-cluster
site_description: User's guide to the PTC cluster at IBS-CTPU
repo_url: https://github.com/cbpark/ptc-cluster/
site_author: Chan Beom Park

extra_javascript: [docs.js]

pages:
    - Home: 'index.md'
    - User Guide:
        - 'Specification' : 'specification.md'
        - 'Job scheduler' : 'job-scheduler.md'
        - 'Environment modules' : 'modules.md'
        - 'Nix' : 'nix.md'
    - Tips and tricks:
        - 'MadGraph' : 'tips-and-tricks/madgraph.md'
    - Admin:
        - 'Administrator Guide' : 'admin/admin-guide.md'

theme: readthedocs