site_name: The PTC cluster at IBS-CTPU
site_url: https://github.com/cbpark/ptc-cluster
site_description: User's guide to the PTC cluster at IBS-CTPU
repo_url: https://github.com/cbpark/ptc-cluster/
site_author: Chan Beom Park

pages:
    - Home: index.md
    - User Guide:
        - specification.md
        - job-scheduler.md
        - modules.md
        - nix.md
    - Tips and tricks:
        - tips-and-tricks/madgraph.md

theme: readthedocs